/*
 * This file is generated by jOOQ.
 */
package win.doyto.ormcamparison.jooq.customer;


import lombok.Data;

import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
@Data
public class Customer implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer cCustkey;
    private String cName;
    private String cAddress;
    private Integer cNationkey;
    private String cPhone;
    private BigDecimal cAcctbal;
    private String cMktsegment;
    private String cComment;

}
